name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write # required for AWS OIDC

jobs:
  apply:
    environment: Production
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.9

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.BACKEND_ROLE }}

      - name: OpenTofu init
        run: |
          tofu init \
              -backend-config="bucket=${{ secrets.BACKEND_BUCKET }}" \
              -backend-config="dynamodb_table=${{ secrets.BACKEND_DDB_TABLE }}"

      - name: OpenTofu validate
        run: tofu validate

      - name: OpenTofu plan
        env:
          OS_APPLICATION_CREDENTIAL_ID: ${{ secrets.OS_APPLICATION_CREDENTIAL_ID }}
          OS_APPLICATION_CREDENTIAL_SECRET: ${{ secrets.OS_APPLICATION_CREDENTIAL_SECRET }}
          OS_AUTH_URL: https://openstack.eqiad1.wikimediacloud.org:25000/v3
          OS_PROJECT_ID: account-creation-assistance
        run: tofu plan -out tfplan
      
      - name: OpenTofu apply
        env:
          OS_APPLICATION_CREDENTIAL_ID: ${{ secrets.OS_APPLICATION_CREDENTIAL_ID }}
          OS_APPLICATION_CREDENTIAL_SECRET: ${{ secrets.OS_APPLICATION_CREDENTIAL_SECRET }}
          OS_AUTH_URL: https://openstack.eqiad1.wikimediacloud.org:25000/v3
          OS_PROJECT_ID: account-creation-assistance
        run: tofu apply tfplan